/*
Deployment script for BeyondFitnessProd5

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO



GO
/*
The column [dbo].[CourseContract].[RegisterID] is being dropped, data loss could occur.
*/

IF EXISTS (select top 1 1 from [dbo].[CourseContract])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The type for column Subject in table [dbo].[EnterpriseCourseContract] is currently  NVARCHAR (64) NULL but is being changed to  NVARCHAR (8) NULL. Data loss could occur.
*/

IF EXISTS (select top 1 1 from [dbo].[EnterpriseCourseContract])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The column [dbo].[GroupingLesson].[RegisterID] is being dropped, data loss could occur.
*/

IF EXISTS (select top 1 1 from [dbo].[GroupingLesson])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The column [dbo].[LessonTimeSettlement].[SettlementID] is being dropped, data loss could occur.
*/

IF EXISTS (select top 1 1 from [dbo].[LessonTimeSettlement])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping [dbo].[FK_RegisterLessonEnterprise_EnterpriseCourseContract]...';


GO
ALTER TABLE [dbo].[RegisterLessonEnterprise] DROP CONSTRAINT [FK_RegisterLessonEnterprise_EnterpriseCourseContract];


GO
PRINT N'Dropping [dbo].[FK_RegisterLessonEnterprise_EnterpriseCourseContent]...';


GO
ALTER TABLE [dbo].[RegisterLessonEnterprise] DROP CONSTRAINT [FK_RegisterLessonEnterprise_EnterpriseCourseContent];


GO
PRINT N'Dropping [dbo].[FK_BodySuffering_BodyDiagnosis]...';


GO
ALTER TABLE [dbo].[BodySuffering] DROP CONSTRAINT [FK_BodySuffering_BodyDiagnosis];


GO
PRINT N'Dropping [dbo].[FK_ContractPayment_CourseContract]...';


GO
ALTER TABLE [dbo].[ContractPayment] DROP CONSTRAINT [FK_ContractPayment_CourseContract];


GO
PRINT N'Dropping [dbo].[FK_ContractTrustSettlement_Settlement]...';


GO
ALTER TABLE [dbo].[ContractTrustSettlement] DROP CONSTRAINT [FK_ContractTrustSettlement_Settlement];


GO
PRINT N'Dropping [dbo].[FK_ContractTrustTrack_CourseContract]...';


GO
ALTER TABLE [dbo].[ContractTrustTrack] DROP CONSTRAINT [FK_ContractTrustTrack_CourseContract];


GO
PRINT N'Dropping [dbo].[FK_ContractTrustTrack_Settlement]...';


GO
ALTER TABLE [dbo].[ContractTrustTrack] DROP CONSTRAINT [FK_ContractTrustTrack_Settlement];


GO
PRINT N'Dropping [dbo].[FK_InvoiceAmountType_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceAmountType] DROP CONSTRAINT [FK_InvoiceAmountType_InvoiceItem];


GO
PRINT N'Dropping [dbo].[FK_InvoiceBuyer_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceBuyer] DROP CONSTRAINT [FK_InvoiceBuyer_InvoiceItem];


GO
PRINT N'Dropping [dbo].[FK_InvoiceCancellation_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceCancellation] DROP CONSTRAINT [FK_InvoiceCancellation_InvoiceItem];


GO
PRINT N'Dropping [dbo].[FK_InvoiceCarrier_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceCarrier] DROP CONSTRAINT [FK_InvoiceCarrier_InvoiceItem];


GO
PRINT N'Dropping [dbo].[FK_InvoiceDetails_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceDetails] DROP CONSTRAINT [FK_InvoiceDetails_InvoiceItem];


GO
PRINT N'Dropping [dbo].[FK_InvoiceDonation_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceDonation] DROP CONSTRAINT [FK_InvoiceDonation_InvoiceItem];


GO
PRINT N'Dropping [dbo].[FK_InvoiceItem_Document]...';


GO
ALTER TABLE [dbo].[InvoiceItem] DROP CONSTRAINT [FK_InvoiceItem_Document];


GO
PRINT N'Dropping [dbo].[FK_InvoiceNoAssignment_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceNoAssignment] DROP CONSTRAINT [FK_InvoiceNoAssignment_InvoiceItem];


GO
PRINT N'Dropping [dbo].[FK_InvoicePurchaseOrder_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoicePurchaseOrder] DROP CONSTRAINT [FK_InvoicePurchaseOrder_InvoiceItem];


GO
PRINT N'Dropping [dbo].[FK_InvoiceSeller_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceSeller] DROP CONSTRAINT [FK_InvoiceSeller_InvoiceItem];


GO
PRINT N'Dropping [dbo].[FK_InvoiceWinningNumber_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceWinningNumber] DROP CONSTRAINT [FK_InvoiceWinningNumber_InvoiceItem];


GO
PRINT N'Dropping [dbo].[FK_LessonTime_ServingCoach]...';


GO
ALTER TABLE [dbo].[LessonTime] DROP CONSTRAINT [FK_LessonTime_ServingCoach];


GO
PRINT N'Dropping [dbo].[FK_Payment_InvoiceItem]...';


GO
ALTER TABLE [dbo].[Payment] DROP CONSTRAINT [FK_Payment_InvoiceItem];


GO
PRINT N'Dropping [dbo].[FK_RegisterLessonContract_RegisterLesson]...';


GO
ALTER TABLE [dbo].[RegisterLessonContract] DROP CONSTRAINT [FK_RegisterLessonContract_RegisterLesson];


GO
PRINT N'Dropping [dbo].[FK_TuitionInstallment_Payment]...';


GO
ALTER TABLE [dbo].[TuitionInstallment] DROP CONSTRAINT [FK_TuitionInstallment_Payment];


GO
PRINT N'Dropping [dbo].[FK_LessonTimeSettlement_Settlement]...';


GO
ALTER TABLE [dbo].[LessonTimeSettlement] DROP CONSTRAINT [FK_LessonTimeSettlement_Settlement];


GO
PRINT N'Dropping <unnamed>...';


GO
EXECUTE sp_droprolemember @rolename = N'db_owner', @membername = N'IIS APPPOOL\.NET v4.5';


GO
PRINT N'Altering [dbo].[CourseContract]...';


GO
ALTER TABLE [dbo].[CourseContract] DROP COLUMN [RegisterID];


GO
PRINT N'Altering [dbo].[EnterpriseCourseContract]...';


GO
ALTER TABLE [dbo].[EnterpriseCourseContract] ALTER COLUMN [Subject] NVARCHAR (8) NULL;


GO
PRINT N'Altering [dbo].[GroupingLesson]...';


GO
ALTER TABLE [dbo].[GroupingLesson] DROP COLUMN [RegisterID];


GO
PRINT N'Altering [dbo].[LessonTimeSettlement]...';


GO
ALTER TABLE [dbo].[LessonTimeSettlement] DROP COLUMN [SettlementID];


GO
PRINT N'Altering [dbo].[RegisterLessonEnterprise]...';


GO
ALTER TABLE [dbo].[RegisterLessonEnterprise] ALTER COLUMN [ContractID] INT NULL;


GO
PRINT N'Creating [dbo].[UserProfileExtension].[IX_UserProfileExtension]...';


GO
CREATE NONCLUSTERED INDEX [IX_UserProfileExtension]
    ON [dbo].[UserProfileExtension]([IDNo] ASC);


GO
PRINT N'Creating [dbo].[FK_RegisterLessonEnterprise_EnterpriseCourseContract]...';


GO
ALTER TABLE [dbo].[RegisterLessonEnterprise] WITH NOCHECK
    ADD CONSTRAINT [FK_RegisterLessonEnterprise_EnterpriseCourseContract] FOREIGN KEY ([ContractID]) REFERENCES [dbo].[EnterpriseCourseContract] ([ContractID]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_RegisterLessonEnterprise_EnterpriseCourseContent]...';


GO
ALTER TABLE [dbo].[RegisterLessonEnterprise] WITH NOCHECK
    ADD CONSTRAINT [FK_RegisterLessonEnterprise_EnterpriseCourseContent] FOREIGN KEY ([ContractID], [TypeID]) REFERENCES [dbo].[EnterpriseCourseContent] ([ContractID], [TypeID]);


GO
PRINT N'Creating [dbo].[FK_BodySuffering_BodyDiagnosis]...';


GO
ALTER TABLE [dbo].[BodySuffering] WITH NOCHECK
    ADD CONSTRAINT [FK_BodySuffering_BodyDiagnosis] FOREIGN KEY ([DiagnosisID]) REFERENCES [dbo].[BodyDiagnosis] ([DiagnosisID]);


GO
PRINT N'Creating [dbo].[FK_ContractPayment_CourseContract]...';


GO
ALTER TABLE [dbo].[ContractPayment] WITH NOCHECK
    ADD CONSTRAINT [FK_ContractPayment_CourseContract] FOREIGN KEY ([ContractID]) REFERENCES [dbo].[CourseContract] ([ContractID]);


GO
PRINT N'Creating [dbo].[FK_ContractTrustSettlement_Settlement]...';


GO
ALTER TABLE [dbo].[ContractTrustSettlement] WITH NOCHECK
    ADD CONSTRAINT [FK_ContractTrustSettlement_Settlement] FOREIGN KEY ([SettlementID]) REFERENCES [dbo].[Settlement] ([SettlementID]);


GO
PRINT N'Creating [dbo].[FK_ContractTrustTrack_CourseContract]...';


GO
ALTER TABLE [dbo].[ContractTrustTrack] WITH NOCHECK
    ADD CONSTRAINT [FK_ContractTrustTrack_CourseContract] FOREIGN KEY ([ContractID]) REFERENCES [dbo].[CourseContract] ([ContractID]);


GO
PRINT N'Creating [dbo].[FK_ContractTrustTrack_Settlement]...';


GO
ALTER TABLE [dbo].[ContractTrustTrack] WITH NOCHECK
    ADD CONSTRAINT [FK_ContractTrustTrack_Settlement] FOREIGN KEY ([SettlementID]) REFERENCES [dbo].[Settlement] ([SettlementID]);


GO
PRINT N'Creating [dbo].[FK_InvoiceAmountType_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceAmountType] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceAmountType_InvoiceItem] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[InvoiceItem] ([InvoiceID]);


GO
PRINT N'Creating [dbo].[FK_InvoiceBuyer_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceBuyer] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceBuyer_InvoiceItem] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[InvoiceItem] ([InvoiceID]);


GO
PRINT N'Creating [dbo].[FK_InvoiceCancellation_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceCancellation] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceCancellation_InvoiceItem] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[InvoiceItem] ([InvoiceID]);


GO
PRINT N'Creating [dbo].[FK_InvoiceCarrier_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceCarrier] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceCarrier_InvoiceItem] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[InvoiceItem] ([InvoiceID]);


GO
PRINT N'Creating [dbo].[FK_InvoiceDetails_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceDetails] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceDetails_InvoiceItem] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[InvoiceItem] ([InvoiceID]);


GO
PRINT N'Creating [dbo].[FK_InvoiceDonation_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceDonation] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceDonation_InvoiceItem] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[InvoiceItem] ([InvoiceID]);


GO
PRINT N'Creating [dbo].[FK_InvoiceItem_Document]...';


GO
ALTER TABLE [dbo].[InvoiceItem] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceItem_Document] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[Document] ([DocID]);


GO
PRINT N'Creating [dbo].[FK_InvoiceNoAssignment_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceNoAssignment] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceNoAssignment_InvoiceItem] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[InvoiceItem] ([InvoiceID]);


GO
PRINT N'Creating [dbo].[FK_InvoicePurchaseOrder_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoicePurchaseOrder] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoicePurchaseOrder_InvoiceItem] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[InvoiceItem] ([InvoiceID]);


GO
PRINT N'Creating [dbo].[FK_InvoiceSeller_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceSeller] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceSeller_InvoiceItem] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[InvoiceItem] ([InvoiceID]);


GO
PRINT N'Creating [dbo].[FK_InvoiceWinningNumber_InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceWinningNumber] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceWinningNumber_InvoiceItem] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[InvoiceItem] ([InvoiceID]);


GO
PRINT N'Creating [dbo].[FK_LessonTime_ServingCoach]...';


GO
ALTER TABLE [dbo].[LessonTime] WITH NOCHECK
    ADD CONSTRAINT [FK_LessonTime_ServingCoach] FOREIGN KEY ([InvitedCoach]) REFERENCES [dbo].[ServingCoach] ([CoachID]);


GO
PRINT N'Creating [dbo].[FK_Payment_InvoiceItem]...';


GO
ALTER TABLE [dbo].[Payment] WITH NOCHECK
    ADD CONSTRAINT [FK_Payment_InvoiceItem] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[InvoiceItem] ([InvoiceID]);


GO
PRINT N'Creating [dbo].[FK_RegisterLessonContract_RegisterLesson]...';


GO
ALTER TABLE [dbo].[RegisterLessonContract] WITH NOCHECK
    ADD CONSTRAINT [FK_RegisterLessonContract_RegisterLesson] FOREIGN KEY ([RegisterID]) REFERENCES [dbo].[RegisterLesson] ([RegisterID]);


GO
PRINT N'Creating [dbo].[FK_TuitionInstallment_Payment]...';


GO
ALTER TABLE [dbo].[TuitionInstallment] WITH NOCHECK
    ADD CONSTRAINT [FK_TuitionInstallment_Payment] FOREIGN KEY ([InstallmentID]) REFERENCES [dbo].[Payment] ([PaymentID]);


GO
PRINT N'Creating [dbo].[V_LearnerFitenessAssessment].[MS_DiagramPane1]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "UserProfile"
            Begin Extent = 
               Top = 9
               Left = 57
               Bottom = 189
               Right = 276
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "UserProfileExtension"
            Begin Extent = 
               Top = 9
               Left = 333
               Bottom = 164
               Right = 552
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "LearnerFitnessAssessment"
            Begin Extent = 
               Top = 9
               Left = 609
               Bottom = 164
               Right = 841
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "LearnerFitnessAssessmentResult"
            Begin Extent = 
               Top = 9
               Left = 898
               Bottom = 164
               Right = 1117
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "FitnessAssessmentItem"
            Begin Extent = 
               Top = 9
               Left = 1174
               Bottom = 164
               Right = 1393
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Fil', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'V_LearnerFitenessAssessment';


GO
PRINT N'Creating [dbo].[V_LearnerFitenessAssessment].[MS_DiagramPane2]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane2', @value = N'ter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'V_LearnerFitenessAssessment';


GO
PRINT N'Creating [dbo].[V_LearnerFitenessAssessment].[MS_DiagramPaneCount]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 2, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'V_LearnerFitenessAssessment';


GO
PRINT N'Checking existing data against newly created constraints';


GO

GO
ALTER TABLE [dbo].[RegisterLessonEnterprise] WITH CHECK CHECK CONSTRAINT [FK_RegisterLessonEnterprise_EnterpriseCourseContract];

ALTER TABLE [dbo].[RegisterLessonEnterprise] WITH CHECK CHECK CONSTRAINT [FK_RegisterLessonEnterprise_EnterpriseCourseContent];

ALTER TABLE [dbo].[BodySuffering] WITH CHECK CHECK CONSTRAINT [FK_BodySuffering_BodyDiagnosis];

ALTER TABLE [dbo].[ContractPayment] WITH CHECK CHECK CONSTRAINT [FK_ContractPayment_CourseContract];

ALTER TABLE [dbo].[ContractTrustSettlement] WITH CHECK CHECK CONSTRAINT [FK_ContractTrustSettlement_Settlement];

ALTER TABLE [dbo].[ContractTrustTrack] WITH CHECK CHECK CONSTRAINT [FK_ContractTrustTrack_CourseContract];

ALTER TABLE [dbo].[ContractTrustTrack] WITH CHECK CHECK CONSTRAINT [FK_ContractTrustTrack_Settlement];

ALTER TABLE [dbo].[InvoiceAmountType] WITH CHECK CHECK CONSTRAINT [FK_InvoiceAmountType_InvoiceItem];

ALTER TABLE [dbo].[InvoiceBuyer] WITH CHECK CHECK CONSTRAINT [FK_InvoiceBuyer_InvoiceItem];

ALTER TABLE [dbo].[InvoiceCancellation] WITH CHECK CHECK CONSTRAINT [FK_InvoiceCancellation_InvoiceItem];

ALTER TABLE [dbo].[InvoiceCarrier] WITH CHECK CHECK CONSTRAINT [FK_InvoiceCarrier_InvoiceItem];

ALTER TABLE [dbo].[InvoiceDetails] WITH CHECK CHECK CONSTRAINT [FK_InvoiceDetails_InvoiceItem];

ALTER TABLE [dbo].[InvoiceDonation] WITH CHECK CHECK CONSTRAINT [FK_InvoiceDonation_InvoiceItem];

ALTER TABLE [dbo].[InvoiceItem] WITH CHECK CHECK CONSTRAINT [FK_InvoiceItem_Document];

ALTER TABLE [dbo].[InvoiceNoAssignment] WITH CHECK CHECK CONSTRAINT [FK_InvoiceNoAssignment_InvoiceItem];

ALTER TABLE [dbo].[InvoicePurchaseOrder] WITH CHECK CHECK CONSTRAINT [FK_InvoicePurchaseOrder_InvoiceItem];

ALTER TABLE [dbo].[InvoiceSeller] WITH CHECK CHECK CONSTRAINT [FK_InvoiceSeller_InvoiceItem];

ALTER TABLE [dbo].[InvoiceWinningNumber] WITH CHECK CHECK CONSTRAINT [FK_InvoiceWinningNumber_InvoiceItem];

ALTER TABLE [dbo].[LessonTime] WITH CHECK CHECK CONSTRAINT [FK_LessonTime_ServingCoach];

ALTER TABLE [dbo].[Payment] WITH CHECK CHECK CONSTRAINT [FK_Payment_InvoiceItem];

ALTER TABLE [dbo].[RegisterLessonContract] WITH CHECK CHECK CONSTRAINT [FK_RegisterLessonContract_RegisterLesson];

ALTER TABLE [dbo].[TuitionInstallment] WITH CHECK CHECK CONSTRAINT [FK_TuitionInstallment_Payment];


GO
PRINT N'Update complete.';


GO
