<?xml version="1.0" encoding="utf-8"?><Database Name="BeyondFitness" Class="BFDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=BeyondFitness;Integrated Security=True" SettingsObjectName="WebHome.Properties.Settings" SettingsPropertyName="BFDbConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserRoleDefinition" Member="UserRoleDefinitions">
    <Type Name="UserRoleDefinition">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SiteMenu" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Association Name="UserRoleDefinition_UserRole" Member="UserRoles" ThisKey="RoleID" OtherKey="RoleID" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.Document" Member="Documents">
    <Type Name="Document">
      <Column Name="DocID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CurrentStep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChannelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Document_Attachment" Member="Attachments" ThisKey="DocID" OtherKey="DocID" Type="Attachment" />
      <Association Name="Document_Article" Member="Article" ThisKey="DocID" OtherKey="DocID" Type="Article" Cardinality="One" />
      <Association Name="DocumentType_Document" Member="DocumentType" ThisKey="DocType" OtherKey="TypeID" Type="DocumentType" IsForeignKey="true" />
      <Association Name="LevelExpression_Document" Member="LevelExpression" ThisKey="CurrentStep" OtherKey="LevelID" Type="LevelExpression" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentType" Member="DocumentTypes">
    <Type Name="DocumentType">
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="DocumentType_Document" Member="Documents" ThisKey="TypeID" OtherKey="DocType" Type="Document" />
    </Type>
  </Table>
  <Table Name="dbo.LevelExpression" Member="LevelExpressions">
    <Type Name="LevelExpression">
      <Column Name="LevelID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Expression" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LevelExpression_Document" Member="Documents" ThisKey="LevelID" OtherKey="CurrentStep" Type="Document" />
      <Association Name="LevelExpression_UserProfile" Member="UserProfiles" ThisKey="LevelID" OtherKey="LevelID" Type="UserProfile" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="UserRoleDefinition_UserRole" Member="UserRoleDefinition" ThisKey="RoleID" OtherKey="RoleID" Type="UserRoleDefinition" IsForeignKey="true" />
      <Association Name="UserProfile_UserRole" Member="UserProfile" ThisKey="UID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Attachment" Member="Attachments">
    <Type Name="Attachment">
      <Column Name="AttachmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StoredPath" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="DocID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Attachment_Article" Member="Articles" ThisKey="AttachmentID" OtherKey="Illustration" Type="Article" />
      <Association Name="Attachment_UserProfile" Member="UserProfiles" ThisKey="AttachmentID" OtherKey="PictureID" Type="UserProfile" />
      <Association Name="Document_Attachment" Member="Document" ThisKey="DocID" OtherKey="DocID" Type="Document" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Article" Member="Articles">
    <Type Name="Article">
      <Column Name="DocID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ArticleContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AuthorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Illustration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Attachment_Article" Member="Attachment" ThisKey="Illustration" OtherKey="AttachmentID" Type="Attachment" IsForeignKey="true" />
      <Association Name="Document_Article" Member="Document" ThisKey="DocID" OtherKey="DocID" Type="Document" IsForeignKey="true" />
      <Association Name="UserProfile_Article" Member="UserProfile" ThisKey="AuthorID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="PID" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="EMail" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Expiration" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Creator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AuthID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThemeName" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Password2" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="MemberCode" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="PictureID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UserProfile_UserRole" Member="UserRoles" ThisKey="UID" OtherKey="UID" Type="UserRole" />
      <Association Name="UserProfile_Article" Member="Articles" ThisKey="UID" OtherKey="AuthorID" Type="Article" />
      <Association Name="UserProfile_UserProfile" Member="UserProfiles" ThisKey="UID" OtherKey="Creator" Type="UserProfile" />
      <Association Name="UserProfile_UserProfile1" Member="UserProfiles1" ThisKey="UID" OtherKey="AuthID" Type="UserProfile" />
      <Association Name="Attachment_UserProfile" Member="Attachment" ThisKey="PictureID" OtherKey="AttachmentID" Type="Attachment" IsForeignKey="true" />
      <Association Name="LevelExpression_UserProfile" Member="LevelExpression" ThisKey="LevelID" OtherKey="LevelID" Type="LevelExpression" IsForeignKey="true" />
      <Association Name="UserProfile_UserProfile" Member="UserProfile1" ThisKey="Creator" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
      <Association Name="UserProfile_UserProfile1" Member="UserProfile2" ThisKey="AuthID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
</Database>