<?xml version="1.0" encoding="utf-8"?><Database Name="BeyondFitness" Class="BFDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=BeyondFitness;Integrated Security=True" SettingsObjectName="WebHome.Properties.Settings" SettingsPropertyName="BFDbConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserRoleDefinition" Member="UserRoleDefinitions">
    <Type Name="UserRoleDefinition">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SiteMenu" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Association Name="UserRoleDefinition_UserRole" Member="UserRole" ThisKey="RoleID" OtherKey="RoleID" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.Document" Member="Documents">
    <Type Name="Document">
      <Column Name="DocID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CurrentStep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChannelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Document_Attachment" Member="Attachments" ThisKey="DocID" OtherKey="DocID" Type="Attachment" />
      <Association Name="Document_Article" Member="Article" ThisKey="DocID" OtherKey="DocID" Type="Article" Cardinality="One" />
      <Association Name="DocumentType_Document" Member="DocumentType" ThisKey="DocType" OtherKey="TypeID" Type="DocumentType" IsForeignKey="true" />
      <Association Name="LevelExpression_Document" Member="LevelExpression" ThisKey="CurrentStep" OtherKey="LevelID" Type="LevelExpression" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentType" Member="DocumentTypes">
    <Type Name="DocumentType">
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="DocumentType_Document" Member="Documents" ThisKey="TypeID" OtherKey="DocType" Type="Document" />
    </Type>
  </Table>
  <Table Name="dbo.LevelExpression" Member="LevelExpressions">
    <Type Name="LevelExpression">
      <Column Name="LevelID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Expression" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LevelExpression_Document" Member="Documents" ThisKey="LevelID" OtherKey="CurrentStep" Type="Document" />
      <Association Name="LevelExpression_LessonPriceType" Member="LessonPriceType" ThisKey="LevelID" OtherKey="Status" Type="LessonPriceType" />
      <Association Name="LevelExpression_RegisterLesson" Member="RegisterLesson" ThisKey="LevelID" OtherKey="Attended" Type="RegisterLesson" />
      <Association Name="LevelExpression_TrainingPlan" Member="TrainingPlan" ThisKey="LevelID" OtherKey="PlanStatus" Type="TrainingPlan" />
      <Association Name="LevelExpression_UserProfile" Member="UserProfile" ThisKey="LevelID" OtherKey="LevelID" Type="UserProfile" />
      <Association Name="LevelExpression_PDQQuestion" Member="PDQQuestion" ThisKey="LevelID" OtherKey="QuestionType" Type="PDQQuestion" />
      <Association Name="LevelExpression_PDQType" Member="PDQType" ThisKey="LevelID" OtherKey="TypeID" Type="PDQType" />
    </Type>
  </Table>
  <Table Name="dbo.Attachment" Member="Attachments">
    <Type Name="Attachment">
      <Column Name="AttachmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StoredPath" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="DocID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Attachment_Article" Member="Articles" ThisKey="AttachmentID" OtherKey="Illustration" Type="Article" />
      <Association Name="Attachment_UserProfile" Member="UserProfile" ThisKey="AttachmentID" OtherKey="PictureID" Type="UserProfile" />
      <Association Name="Document_Attachment" Member="Document" ThisKey="DocID" OtherKey="DocID" Type="Document" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Article" Member="Articles">
    <Type Name="Article">
      <Column Name="DocID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ArticleContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AuthorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Illustration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Attachment_Article" Member="Attachment" ThisKey="Illustration" OtherKey="AttachmentID" Type="Attachment" IsForeignKey="true" />
      <Association Name="Document_Article" Member="Document" ThisKey="DocID" OtherKey="DocID" Type="Document" IsForeignKey="true" />
      <Association Name="UserProfile_Article" Member="UserProfile" ThisKey="AuthorID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRole">
    <Type Name="UserRole">
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="UserRoleDefinition_UserRole" Member="UserRoleDefinition" ThisKey="RoleID" OtherKey="RoleID" Type="UserRoleDefinition" IsForeignKey="true" />
      <Association Name="UserProfile_UserRole" Member="UserProfile" ThisKey="UID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ResetPassword" Member="ResetPasswords">
    <Type Name="ResetPassword">
      <Column Name="ResetID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserProfile_ResetPassword" Member="UserProfile" ThisKey="UID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServingCoach" Member="ServingCoach">
    <Type Name="ServingCoach">
      <Column Name="CoachID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ServingCoach_LessonTime" Member="InvitingLesson" Storage="_LessonTime" ThisKey="CoachID" OtherKey="InvitedCoach" Type="LessonTime" />
      <Association Name="ServingCoach_LessonTime1" Member="TeachingLesson" Storage="_LessonTime1" ThisKey="CoachID" OtherKey="AttendingCoach" Type="LessonTime" />
      <Association Name="UserProfile_ServingCoach" Member="UserProfile" ThisKey="CoachID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LessonPriceType" Member="LessonPriceType">
    <Type Name="LessonPriceType">
      <Column Name="PriceID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ListPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LessonPriceType_RegisterLesson" Member="RegisterLesson" ThisKey="PriceID" OtherKey="ClassLevel" Type="RegisterLesson" />
      <Association Name="LevelExpression_LessonPriceType" Member="LevelExpression" ThisKey="Status" OtherKey="LevelID" Type="LevelExpression" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GroupingLesson" Member="GroupingLesson">
    <Type Name="GroupingLesson">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="GroupingLesson_RegisterLesson" Member="RegisterLesson" ThisKey="GroupID" OtherKey="RegisterGroupID" Type="RegisterLesson" />
      <Association Name="GroupingLesson_LessonTime" Member="LessonTime" ThisKey="GroupID" OtherKey="GroupID" Type="LessonTime" />
    </Type>
  </Table>
  <Table Name="dbo.RegisterLesson" Member="RegisterLesson">
    <Type Name="RegisterLesson">
      <Column Name="RegisterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegisterDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Lessons" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attended" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegisterGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupingMemberCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="RegisterLesson_LessonTime" Member="LessonTime" ThisKey="RegisterID" OtherKey="RegisterID" Type="LessonTime" />
      <Association Name="RegisterLesson_LessonTimeExpansion" Member="LessonTimeExpansion" ThisKey="RegisterID" OtherKey="RegisterID" Type="LessonTimeExpansion" />
      <Association Name="GroupingLesson_RegisterLesson" Member="GroupingLesson" ThisKey="RegisterGroupID" OtherKey="GroupID" Type="GroupingLesson" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="LessonPriceType_RegisterLesson" Member="LessonPriceType" ThisKey="ClassLevel" OtherKey="PriceID" Type="LessonPriceType" IsForeignKey="true" />
      <Association Name="LevelExpression_RegisterLesson" Member="LevelExpression" ThisKey="Attended" OtherKey="LevelID" Type="LevelExpression" IsForeignKey="true" />
      <Association Name="UserProfile_RegisterLesson" Member="UserProfile" ThisKey="UID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LessonTime" Member="LessonTime">
    <Type Name="LessonTime">
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegisterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DurationInMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvitedCoach" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttendingCoach" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LessonTime_LessonTimeExpansion" Member="LessonTimeExpansion" ThisKey="LessonID" OtherKey="LessonID" Type="LessonTimeExpansion" />
      <Association Name="LessonTime_LessonPlan" Member="LessonPlan" ThisKey="LessonID" OtherKey="LessonID" Type="LessonPlan" Cardinality="One" />
      <Association Name="LessonTime_TrainingPlan" Member="TrainingPlan" ThisKey="LessonID" OtherKey="LessonID" Type="TrainingPlan" />
      <Association Name="LessonTime_FitnessAssessment" Member="FitnessAssessment" ThisKey="LessonID" OtherKey="LessonID" Type="FitnessAssessment" Cardinality="One" />
      <Association Name="LessonTime_LessonTrend" Member="LessonTrend" ThisKey="LessonID" OtherKey="LessonID" Type="LessonTrend" Cardinality="One" />
      <Association Name="LessonTime_LessonAttendance" Member="LessonAttendance" ThisKey="LessonID" OtherKey="LessonID" Type="LessonAttendance" Cardinality="One" />
      <Association Name="GroupingLesson_LessonTime" Member="GroupingLesson" ThisKey="GroupID" OtherKey="GroupID" Type="GroupingLesson" IsForeignKey="true" />
      <Association Name="RegisterLesson_LessonTime" Member="RegisterLesson" ThisKey="RegisterID" OtherKey="RegisterID" Type="RegisterLesson" IsForeignKey="true" />
      <Association Name="ServingCoach_LessonTime" Member="AsInvitedCoach" Storage="_ServingCoach" ThisKey="InvitedCoach" OtherKey="CoachID" Type="ServingCoach" IsForeignKey="true" />
      <Association Name="ServingCoach_LessonTime1" Member="AsAttendingCoach" Storage="_ServingCoach1" ThisKey="AttendingCoach" OtherKey="CoachID" Type="ServingCoach" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LessonTimeExpansion" Member="LessonTimeExpansion">
    <Type Name="LessonTimeExpansion">
      <Column Name="ClassDate" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Hour" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegisterID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LessonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LessonTime_LessonTimeExpansion" Member="LessonTime" ThisKey="LessonID" OtherKey="LessonID" Type="LessonTime" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="RegisterLesson_LessonTimeExpansion" Member="RegisterLesson" ThisKey="RegisterID" OtherKey="RegisterID" Type="RegisterLesson" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrainingType" Member="TrainingType">
    <Type Name="TrainingType">
      <Column Name="TrainingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BodyParts" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Association Name="TrainingType_TrainingItem" Member="TrainingItem" ThisKey="TrainingID" OtherKey="TrainingID" Type="TrainingItem" />
    </Type>
  </Table>
  <Table Name="dbo.LessonPlan" Member="LessonPlan">
    <Type Name="LessonPlan">
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Warming" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RecentStatus" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EndingOperation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FeedBack" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="LessonTime_LessonPlan" Member="LessonTime" ThisKey="LessonID" OtherKey="LessonID" Type="LessonTime" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrainingPlan" Member="TrainingPlan">
    <Type Name="TrainingPlan">
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExecutionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlanStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TrainingPlan_TrainingExecution" Member="TrainingExecution" ThisKey="ExecutionID" OtherKey="ExecutionID" Type="TrainingExecution" Cardinality="One" />
      <Association Name="LessonTime_TrainingPlan" Member="LessonTime" ThisKey="LessonID" OtherKey="LessonID" Type="LessonTime" IsForeignKey="true" />
      <Association Name="LevelExpression_TrainingPlan" Member="LevelExpression" ThisKey="PlanStatus" OtherKey="LevelID" Type="LevelExpression" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FitnessAssessment" Member="FitnessAssessment">
    <Type Name="FitnessAssessment">
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Flexibility" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cardiopulmonary" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Strength" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Endurance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExplosiveForce" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SportsPerformance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LessonTime_FitnessAssessment" Member="LessonTime" ThisKey="LessonID" OtherKey="LessonID" Type="LessonTime" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LessonTrend" Member="LessonTrend">
    <Type Name="LessonTrend">
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ActionLearning" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostureRedress" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Training" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LessonTime_LessonTrend" Member="LessonTime" ThisKey="LessonID" OtherKey="LessonID" Type="LessonTime" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrainingExecution" Member="TrainingExecution">
    <Type Name="TrainingExecution">
      <Column Name="ExecutionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BreakIntervalInSecond" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Repeats" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActualBreakIntervalInSecond" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActualRepeats" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Conclusion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ExecutionFeedBack" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="TrainingExecution_TrainingItem" Member="TrainingItem" ThisKey="ExecutionID" OtherKey="ExecutionID" Type="TrainingItem" />
      <Association Name="TrainingPlan_TrainingExecution" Member="TrainingPlan" ThisKey="ExecutionID" OtherKey="ExecutionID" Type="TrainingPlan" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LessonAttendance" Member="LessonAttendance">
    <Type Name="LessonAttendance">
      <Column Name="LessonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompleteDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="LessonTime_LessonAttendance" Member="LessonTime" ThisKey="LessonID" OtherKey="LessonID" Type="LessonTime" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfile">
    <Type Name="UserProfile">
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="PID" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ExternalID" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Expiration" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Creator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AuthID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThemeName" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Password2" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="MemberCode" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="PictureID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RealName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="RecentStatus" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="UserProfile_Article" Member="Article" ThisKey="UID" OtherKey="AuthorID" Type="Article" />
      <Association Name="UserProfile_UserRole" Member="UserRole" ThisKey="UID" OtherKey="UID" Type="UserRole" />
      <Association Name="UserProfile_ResetPassword" Member="ResetPassword" ThisKey="UID" OtherKey="UID" Type="ResetPassword" />
      <Association Name="UserProfile_ServingCoach" Member="ServingCoach" ThisKey="UID" OtherKey="CoachID" Type="ServingCoach" Cardinality="One" />
      <Association Name="UserProfile_RegisterLesson" Member="RegisterLesson" ThisKey="UID" OtherKey="UID" Type="RegisterLesson" />
      <Association Name="UserProfile_UserProfile" Member="UserProfile2" ThisKey="UID" OtherKey="Creator" Type="UserProfile" />
      <Association Name="UserProfile_UserProfile1" Member="UserProfile4" ThisKey="UID" OtherKey="AuthID" Type="UserProfile" />
      <Association Name="UserProfile_PDQTask" Member="PDQTask" ThisKey="UID" OtherKey="UID" Type="PDQTask" />
      <Association Name="UserProfile_PDQUserAssessment" Member="PDQUserAssessment" ThisKey="UID" OtherKey="UID" Type="PDQUserAssessment" Cardinality="One" />
      <Association Name="Attachment_UserProfile" Member="Attachment" ThisKey="PictureID" OtherKey="AttachmentID" Type="Attachment" IsForeignKey="true" />
      <Association Name="LevelExpression_UserProfile" Member="LevelExpression" ThisKey="LevelID" OtherKey="LevelID" Type="LevelExpression" IsForeignKey="true" />
      <Association Name="UserProfile_UserProfile" Member="UserProfile1" ThisKey="Creator" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
      <Association Name="UserProfile_UserProfile1" Member="UserProfile3" ThisKey="AuthID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GoalAboutPDQ" Member="GoalAboutPDQ">
    <Type Name="GoalAboutPDQ">
      <Column Name="GoalID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Goal" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Association Name="GoalAboutPDQ_PDQUserAssessment" Member="PDQUserAssessment" ThisKey="GoalID" OtherKey="GoalID" Type="PDQUserAssessment" />
    </Type>
  </Table>
  <Table Name="dbo.PDQQuestion" Member="PDQQuestion">
    <Type Name="PDQQuestion">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="QuestionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RightAnswer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="QuestionNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PDQQuestion_PDQSuggestion" Member="PDQSuggestion" ThisKey="QuestionID" OtherKey="QuestionID" Type="PDQSuggestion" />
      <Association Name="PDQQuestion_PDQTask" Member="PDQTask" ThisKey="QuestionID" OtherKey="QuestionID" Type="PDQTask" />
      <Association Name="PDQQuestion_PDQType" Member="PDQType" ThisKey="QuestionID" OtherKey="QuestionID" Type="PDQType" Cardinality="One" />
      <Association Name="LevelExpression_PDQQuestion" Member="LevelExpression" ThisKey="QuestionType" OtherKey="LevelID" Type="LevelExpression" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PDQSuggestion" Member="PDQSuggestion">
    <Type Name="PDQSuggestion">
      <Column Name="SuggestionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Suggestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="RightAnswer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PDQSuggestion_PDQTask" Member="PDQTask" ThisKey="SuggestionID" OtherKey="SuggestionID" Type="PDQTask" />
      <Association Name="PDQQuestion_PDQSuggestion" Member="PDQQuestion" ThisKey="QuestionID" OtherKey="QuestionID" Type="PDQQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PDQTask" Member="PDQTask">
    <Type Name="PDQTask">
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SuggestionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PDQAnswer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="YesOrNo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PDQQuestion_PDQTask" Member="PDQQuestion" ThisKey="QuestionID" OtherKey="QuestionID" Type="PDQQuestion" IsForeignKey="true" />
      <Association Name="PDQSuggestion_PDQTask" Member="PDQSuggestion" ThisKey="SuggestionID" OtherKey="SuggestionID" Type="PDQSuggestion" IsForeignKey="true" />
      <Association Name="UserProfile_PDQTask" Member="UserProfile" ThisKey="UID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PDQType" Member="PDQType">
    <Type Name="PDQType">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LevelExpression_PDQType" Member="LevelExpression" ThisKey="TypeID" OtherKey="LevelID" Type="LevelExpression" IsForeignKey="true" />
      <Association Name="PDQQuestion_PDQType" Member="PDQQuestion" ThisKey="QuestionID" OtherKey="QuestionID" Type="PDQQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PDQUserAssessment" Member="PDQUserAssessment">
    <Type Name="PDQUserAssessment">
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GoalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StyleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GoalAboutPDQ_PDQUserAssessment" Member="GoalAboutPDQ" ThisKey="GoalID" OtherKey="GoalID" Type="GoalAboutPDQ" IsForeignKey="true" />
      <Association Name="UserProfile_PDQUserAssessment" Member="UserProfile" ThisKey="UID" OtherKey="UID" Type="UserProfile" IsForeignKey="true" />
      <Association Name="StyleAboutPDQ_PDQUserAssessment" Member="StyleAboutPDQ" ThisKey="StyleID" OtherKey="StyleID" Type="StyleAboutPDQ" IsForeignKey="true" />
      <Association Name="TrainingLevelAboutPDQ_PDQUserAssessment" Member="TrainingLevelAboutPDQ" ThisKey="LevelID" OtherKey="LevelID" Type="TrainingLevelAboutPDQ" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StyleAboutPDQ" Member="StyleAboutPDQ">
    <Type Name="StyleAboutPDQ">
      <Column Name="StyleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Style" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Association Name="StyleAboutPDQ_PDQUserAssessment" Member="PDQUserAssessment" ThisKey="StyleID" OtherKey="StyleID" Type="PDQUserAssessment" />
    </Type>
  </Table>
  <Table Name="dbo.TrainingLevelAboutPDQ" Member="TrainingLevelAboutPDQ">
    <Type Name="TrainingLevelAboutPDQ">
      <Column Name="LevelID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TrainingLevel" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Association Name="TrainingLevelAboutPDQ_PDQUserAssessment" Member="PDQUserAssessment" ThisKey="LevelID" OtherKey="LevelID" Type="PDQUserAssessment" />
    </Type>
  </Table>
  <Table Name="dbo.TrainingItem" Member="TrainingItem">
    <Type Name="TrainingItem">
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TrainingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GoalTurns" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="GoalStrength" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="ExecutionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="ActualStrength" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="ActualTurns" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Association Name="TrainingExecution_TrainingItem" Member="TrainingExecution" ThisKey="ExecutionID" OtherKey="ExecutionID" Type="TrainingExecution" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TrainingType_TrainingItem" Member="TrainingType" ThisKey="TrainingID" OtherKey="TrainingID" Type="TrainingType" IsForeignKey="true" />
    </Type>
  </Table>
</Database>