xcopy Controllers \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\Controllers /s/d/v/f
xcopy ..\beyond-fitness\Controllers \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\Controllers /s/d/v/f
xcopy ..\beyond-fitness\Views \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\Views /s/d/v/f
xcopy Views\ConsoleHome \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\Views\ConsoleHome /s/d/v/f
xcopy Views\ConsoleEvent \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\Views\ConsoleEvent /s/d/v/f
xcopy Views\ContractConsole \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\Views\ContractConsole /s/d/v/f
xcopy Views\LessonConsole \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\Views\LessonConsole /s/d/v/f
xcopy Views\ReportConsole \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\Views\ReportConsole /s/d/v/f
xcopy Views\MainActivity \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\Views\MainActivity /s/d/v/f
xcopy Views\Blog \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\Views\Blog /s/d/v/f
xcopy bin \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\bin /s/d/v/f
xcopy ConsoleHome \\VM-Venus\E$\Project\GitHub\beyond-fitness\beyond-fitness\ConsoleHome /s/d/v/f/c
