//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFConsole.Views.MainActivity.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamingItem {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamingItem() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BFConsole.Views.MainActivity.Resources.NamingItem", typeof(NamingItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        public static string FindUs {
            get {
                return ResourceManager.GetString("FindUs", resourceCulture);
            }
        }
        
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        public static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        public static string ContactSubTitle {
            get {
                return ResourceManager.GetString("ContactSubTitle", resourceCulture);
            }
        }
        
        public static string ContactAskNow {
            get {
                return ResourceManager.GetString("ContactAskNow", resourceCulture);
            }
        }
        
        public static string IndexBannerTitle {
            get {
                return ResourceManager.GetString("IndexBannerTitle", resourceCulture);
            }
        }
        
        public static string IndexBannerSubTitle {
            get {
                return ResourceManager.GetString("IndexBannerSubTitle", resourceCulture);
            }
        }
        
        public static string IndexFeature1 {
            get {
                return ResourceManager.GetString("IndexFeature1", resourceCulture);
            }
        }
        
        public static string IndexFeature1Desc {
            get {
                return ResourceManager.GetString("IndexFeature1Desc", resourceCulture);
            }
        }
        
        public static string IndexFeature2 {
            get {
                return ResourceManager.GetString("IndexFeature2", resourceCulture);
            }
        }
        
        public static string IndexFeature2Desc {
            get {
                return ResourceManager.GetString("IndexFeature2Desc", resourceCulture);
            }
        }
        
        public static string IndexFeature3 {
            get {
                return ResourceManager.GetString("IndexFeature3", resourceCulture);
            }
        }
        
        public static string IndexFeature3Desc {
            get {
                return ResourceManager.GetString("IndexFeature3Desc", resourceCulture);
            }
        }
        
        public static string IndexVedioTitle {
            get {
                return ResourceManager.GetString("IndexVedioTitle", resourceCulture);
            }
        }
        
        public static string IndexVedioSubTitle {
            get {
                return ResourceManager.GetString("IndexVedioSubTitle", resourceCulture);
            }
        }
        
        public static string IndexVedioDesc {
            get {
                return ResourceManager.GetString("IndexVedioDesc", resourceCulture);
            }
        }
        
        public static string IndexFunFactsTitle {
            get {
                return ResourceManager.GetString("IndexFunFactsTitle", resourceCulture);
            }
        }
        
        public static string IndexSlick1Desc {
            get {
                return ResourceManager.GetString("IndexSlick1Desc", resourceCulture);
            }
        }
        
        public static string IndexSlick1Title {
            get {
                return ResourceManager.GetString("IndexSlick1Title", resourceCulture);
            }
        }
        
        public static string IndexSlick1Name {
            get {
                return ResourceManager.GetString("IndexSlick1Name", resourceCulture);
            }
        }
        
        public static string IndexSlick2Desc {
            get {
                return ResourceManager.GetString("IndexSlick2Desc", resourceCulture);
            }
        }
        
        public static string IndexSlick2Title {
            get {
                return ResourceManager.GetString("IndexSlick2Title", resourceCulture);
            }
        }
        
        public static string IndexSlick2Name {
            get {
                return ResourceManager.GetString("IndexSlick2Name", resourceCulture);
            }
        }
        
        public static string AboutBannerTitle {
            get {
                return ResourceManager.GetString("AboutBannerTitle", resourceCulture);
            }
        }
        
        public static string AboutBannerSubTitle {
            get {
                return ResourceManager.GetString("AboutBannerSubTitle", resourceCulture);
            }
        }
        
        public static string AboutVedioTitle {
            get {
                return ResourceManager.GetString("AboutVedioTitle", resourceCulture);
            }
        }
        
        public static string AboutVedioDesc1 {
            get {
                return ResourceManager.GetString("AboutVedioDesc1", resourceCulture);
            }
        }
        
        public static string AboutVedioDesc2 {
            get {
                return ResourceManager.GetString("AboutVedioDesc2", resourceCulture);
            }
        }
        
        public static string AboutVedioDesc3 {
            get {
                return ResourceManager.GetString("AboutVedioDesc3", resourceCulture);
            }
        }
        
        public static string AboutVedioDesc4 {
            get {
                return ResourceManager.GetString("AboutVedioDesc4", resourceCulture);
            }
        }
        
        public static string AboutVedioDeclaration1 {
            get {
                return ResourceManager.GetString("AboutVedioDeclaration1", resourceCulture);
            }
        }
        
        public static string FindNanjingBranch {
            get {
                return ResourceManager.GetString("FindNanjingBranch", resourceCulture);
            }
        }
        
        public static string FindNanjingBranchAdd {
            get {
                return ResourceManager.GetString("FindNanjingBranchAdd", resourceCulture);
            }
        }
        
        public static string FindNanjingBranchDesc1 {
            get {
                return ResourceManager.GetString("FindNanjingBranchDesc1", resourceCulture);
            }
        }
        
        public static string FindNanjingBranchDesc2 {
            get {
                return ResourceManager.GetString("FindNanjingBranchDesc2", resourceCulture);
            }
        }
        
        public static string FindXinyiBranch {
            get {
                return ResourceManager.GetString("FindXinyiBranch", resourceCulture);
            }
        }
        
        public static string FindXinyiBranchAdd {
            get {
                return ResourceManager.GetString("FindXinyiBranchAdd", resourceCulture);
            }
        }
        
        public static string FindXinyiBranchDesc1 {
            get {
                return ResourceManager.GetString("FindXinyiBranchDesc1", resourceCulture);
            }
        }
        
        public static string FindXinyiBranchDesc2 {
            get {
                return ResourceManager.GetString("FindXinyiBranchDesc2", resourceCulture);
            }
        }
        
        public static string FindZhongxiaoBranch {
            get {
                return ResourceManager.GetString("FindZhongxiaoBranch", resourceCulture);
            }
        }
        
        public static string FindZhongxiaoBranchAdd {
            get {
                return ResourceManager.GetString("FindZhongxiaoBranchAdd", resourceCulture);
            }
        }
        
        public static string FindZhongxiaoBranchDesc1 {
            get {
                return ResourceManager.GetString("FindZhongxiaoBranchDesc1", resourceCulture);
            }
        }
        
        public static string FindZhongxiaoBranchDesc2 {
            get {
                return ResourceManager.GetString("FindZhongxiaoBranchDesc2", resourceCulture);
            }
        }
        
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        public static string JoinUsTitle {
            get {
                return ResourceManager.GetString("JoinUsTitle", resourceCulture);
            }
        }
        
        public static string JoinUsDesc {
            get {
                return ResourceManager.GetString("JoinUsDesc", resourceCulture);
            }
        }
        
        public static string JoinUsFeature1 {
            get {
                return ResourceManager.GetString("JoinUsFeature1", resourceCulture);
            }
        }
        
        public static string JoinUsFeature1Desc {
            get {
                return ResourceManager.GetString("JoinUsFeature1Desc", resourceCulture);
            }
        }
        
        public static string JoinUsFeature2 {
            get {
                return ResourceManager.GetString("JoinUsFeature2", resourceCulture);
            }
        }
        
        public static string JoinUsFeature2Desc {
            get {
                return ResourceManager.GetString("JoinUsFeature2Desc", resourceCulture);
            }
        }
        
        public static string JoinUsFeature3 {
            get {
                return ResourceManager.GetString("JoinUsFeature3", resourceCulture);
            }
        }
        
        public static string JoinUsFeature3Desc {
            get {
                return ResourceManager.GetString("JoinUsFeature3Desc", resourceCulture);
            }
        }
        
        public static string JoinUsFeature4 {
            get {
                return ResourceManager.GetString("JoinUsFeature4", resourceCulture);
            }
        }
        
        public static string JoinUsFeature4Desc {
            get {
                return ResourceManager.GetString("JoinUsFeature4Desc", resourceCulture);
            }
        }
        
        public static string JoinUsJob1 {
            get {
                return ResourceManager.GetString("JoinUsJob1", resourceCulture);
            }
        }
        
        public static string JoinUsJob1Desc {
            get {
                return ResourceManager.GetString("JoinUsJob1Desc", resourceCulture);
            }
        }
        
        public static string JoinUsJob2 {
            get {
                return ResourceManager.GetString("JoinUsJob2", resourceCulture);
            }
        }
        
        public static string JoinUsJob2Desc {
            get {
                return ResourceManager.GetString("JoinUsJob2Desc", resourceCulture);
            }
        }
        
        public static string OpportunityBannerTitle {
            get {
                return ResourceManager.GetString("OpportunityBannerTitle", resourceCulture);
            }
        }
        
        public static string OpportunityBannerSubTitle {
            get {
                return ResourceManager.GetString("OpportunityBannerSubTitle", resourceCulture);
            }
        }
        
        public static string OpportunityFeaturesTitle {
            get {
                return ResourceManager.GetString("OpportunityFeaturesTitle", resourceCulture);
            }
        }
        
        public static string OpportunityFeaturesDesc1 {
            get {
                return ResourceManager.GetString("OpportunityFeaturesDesc1", resourceCulture);
            }
        }
        
        public static string OpportunityFeaturesDesc2 {
            get {
                return ResourceManager.GetString("OpportunityFeaturesDesc2", resourceCulture);
            }
        }
        
        public static string OpportunityFeaturesDesc3 {
            get {
                return ResourceManager.GetString("OpportunityFeaturesDesc3", resourceCulture);
            }
        }
        
        public static string OpportunityFeaturesDesc4 {
            get {
                return ResourceManager.GetString("OpportunityFeaturesDesc4", resourceCulture);
            }
        }
        
        public static string JoinUsContactTitle {
            get {
                return ResourceManager.GetString("JoinUsContactTitle", resourceCulture);
            }
        }
        
        public static string JoinUsContactDesc {
            get {
                return ResourceManager.GetString("JoinUsContactDesc", resourceCulture);
            }
        }
        
        public static string HereWeGo {
            get {
                return ResourceManager.GetString("HereWeGo", resourceCulture);
            }
        }
        
        public static string AboutVedioDeclaration2 {
            get {
                return ResourceManager.GetString("AboutVedioDeclaration2", resourceCulture);
            }
        }
        
        public static string BookNowTitle {
            get {
                return ResourceManager.GetString("BookNowTitle", resourceCulture);
            }
        }
        
        public static string BookNowStep1 {
            get {
                return ResourceManager.GetString("BookNowStep1", resourceCulture);
            }
        }
        
        public static string BookNowStep2 {
            get {
                return ResourceManager.GetString("BookNowStep2", resourceCulture);
            }
        }
        
        public static string BookNowStep3 {
            get {
                return ResourceManager.GetString("BookNowStep3", resourceCulture);
            }
        }
        
        public static string BookNowStep4 {
            get {
                return ResourceManager.GetString("BookNowStep4", resourceCulture);
            }
        }
        
        public static string Features1Desc {
            get {
                return ResourceManager.GetString("Features1Desc", resourceCulture);
            }
        }
        
        public static string Features2Desc {
            get {
                return ResourceManager.GetString("Features2Desc", resourceCulture);
            }
        }
        
        public static string Features3Desc {
            get {
                return ResourceManager.GetString("Features3Desc", resourceCulture);
            }
        }
        
        public static string FAQBannerTitle {
            get {
                return ResourceManager.GetString("FAQBannerTitle", resourceCulture);
            }
        }
        
        public static string FAQQestion1 {
            get {
                return ResourceManager.GetString("FAQQestion1", resourceCulture);
            }
        }
        
        public static string FAQQestion11 {
            get {
                return ResourceManager.GetString("FAQQestion11", resourceCulture);
            }
        }
        
        public static string FAQQestion12 {
            get {
                return ResourceManager.GetString("FAQQestion12", resourceCulture);
            }
        }
        
        public static string FAQQestion13 {
            get {
                return ResourceManager.GetString("FAQQestion13", resourceCulture);
            }
        }
        
        public static string FAQQestion2 {
            get {
                return ResourceManager.GetString("FAQQestion2", resourceCulture);
            }
        }
        
        public static string FAQQestion21 {
            get {
                return ResourceManager.GetString("FAQQestion21", resourceCulture);
            }
        }
        
        public static string FAQQestion22 {
            get {
                return ResourceManager.GetString("FAQQestion22", resourceCulture);
            }
        }
        
        public static string FAQQestion3 {
            get {
                return ResourceManager.GetString("FAQQestion3", resourceCulture);
            }
        }
        
        public static string FAQQestion4 {
            get {
                return ResourceManager.GetString("FAQQestion4", resourceCulture);
            }
        }
        
        public static string FAQQestion5 {
            get {
                return ResourceManager.GetString("FAQQestion5", resourceCulture);
            }
        }
        
        public static string FAQAnswer11 {
            get {
                return ResourceManager.GetString("FAQAnswer11", resourceCulture);
            }
        }
        
        public static string FAQAnswer12 {
            get {
                return ResourceManager.GetString("FAQAnswer12", resourceCulture);
            }
        }
        
        public static string FAQAnswer13 {
            get {
                return ResourceManager.GetString("FAQAnswer13", resourceCulture);
            }
        }
        
        public static string FAQAnswer21 {
            get {
                return ResourceManager.GetString("FAQAnswer21", resourceCulture);
            }
        }
        
        public static string FAQAnswer22 {
            get {
                return ResourceManager.GetString("FAQAnswer22", resourceCulture);
            }
        }
        
        public static string FAQAnswer3 {
            get {
                return ResourceManager.GetString("FAQAnswer3", resourceCulture);
            }
        }
        
        public static string FAQAnswer4 {
            get {
                return ResourceManager.GetString("FAQAnswer4", resourceCulture);
            }
        }
        
        public static string FAQAnswer5 {
            get {
                return ResourceManager.GetString("FAQAnswer5", resourceCulture);
            }
        }
        
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        public static string OnlineReservation {
            get {
                return ResourceManager.GetString("OnlineReservation", resourceCulture);
            }
        }
        
        public static string TeamTitle {
            get {
                return ResourceManager.GetString("TeamTitle", resourceCulture);
            }
        }
        
        public static string BlogBack {
            get {
                return ResourceManager.GetString("BlogBack", resourceCulture);
            }
        }
        
        public static string PricingTitle {
            get {
                return ResourceManager.GetString("PricingTitle", resourceCulture);
            }
        }
    }
}
