//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHome.Views.MainActivity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamingItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamingItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebHome.Views.MainActivity.Resources.NamingItem", typeof(NamingItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一種令人微笑的信任.
        /// </summary>
        public static string AboutBannerSubTitle {
            get {
                return ResourceManager.GetString("AboutBannerSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 專業起於真誠.
        /// </summary>
        public static string AboutBannerTitle {
            get {
                return ResourceManager.GetString("AboutBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於我們.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 謝謝您，.
        /// </summary>
        public static string AboutVedioDeclaration1 {
            get {
                return ResourceManager.GetString("AboutVedioDeclaration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們將一起創造專屬於你的價值，進而讓生活更有意義。.
        /// </summary>
        public static string AboutVedioDeclaration2 {
            get {
                return ResourceManager.GetString("AboutVedioDeclaration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeyondFitness 於2014年所創立，是全台最大運動客製化訓練中心之一，擁有超過50位員工，提供包括個人客製化運動訓練服務，企業團隊健康策略，專業運動教育培訓，與企業健康顧問等服務。.
        /// </summary>
        public static string AboutVedioDesc1 {
            get {
                return ResourceManager.GetString("AboutVedioDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 對 BeyondFitness 來說，運動是一件認真的事情。.
        /// </summary>
        public static string AboutVedioDesc2 {
            get {
                return ResourceManager.GetString("AboutVedioDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作為一個專業的體能顧問，我們帶著真誠藉由科學與數據條理化的方法與您相互合作，為每一次的運動帶來最高效益與價值。.
        /// </summary>
        public static string AboutVedioDesc3 {
            get {
                return ResourceManager.GetString("AboutVedioDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們相信「若能幫助您成功的改變生活、邁向健康，自然而然可透過運動創造屬於您的人本價值及生活品質。」.
        /// </summary>
        public static string AboutVedioDesc4 {
            get {
                return ResourceManager.GetString("AboutVedioDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品牌信念.
        /// </summary>
        public static string AboutVedioTitle {
            get {
                return ResourceManager.GetString("AboutVedioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 知識分享.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回官網首頁.
        /// </summary>
        public static string BlogBack {
            get {
                return ResourceManager.GetString("BlogBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 預約諮詢.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 預約&lt;span&gt;可直接透過線上，電話，E-Mail 與專業人員預約時間以及了解內容&lt;/span&gt;.
        /// </summary>
        public static string BookNowStep1 {
            get {
                return ResourceManager.GetString("BookNowStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 諮詢&lt;span&gt;我們將細心地瞭解您的狀況以及需求來幫助您，同時告知體驗相關流程，讓您放心理解細節&lt;/span&gt;.
        /// </summary>
        public static string BookNowStep2 {
            get {
                return ResourceManager.GetString("BookNowStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 體驗&lt;span&gt;輕鬆的前往各分店，專業人員將針對您的狀況帶您做一次適合的運動，並同時可以了解自身狀況以及運動流程以及環境&lt;/span&gt;.
        /// </summary>
        public static string BookNowStep3 {
            get {
                return ResourceManager.GetString("BookNowStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 量身定做&lt;span&gt;專業人員將與您解釋詳細運動細節以及身體狀況，並一同討論您的狀況以及給予真正適合您的建議&lt;/span&gt;.
        /// </summary>
        public static string BookNowStep4 {
            get {
                return ResourceManager.GetString("BookNowStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 諮詢四步驟.
        /// </summary>
        public static string BookNowTitle {
            get {
                return ResourceManager.GetString("BookNowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即提問.
        /// </summary>
        public static string ContactAskNow {
            get {
                return ResourceManager.GetString("ContactAskNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們隨時提供協助。.
        /// </summary>
        public static string ContactSubTitle {
            get {
                return ResourceManager.GetString("ContactSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始您的第一步.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常見問題.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有的！體驗課程需要提前 1~2日 預約，您就可以準備體驗您的快樂運動時光。.
        /// </summary>
        public static string FAQAnswer11 {
            get {
                return ResourceManager.GetString("FAQAnswer11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 體驗課程如下： &lt;li&gt;您將會了解您的身體狀況諮詢服務。&lt;/li&gt;&lt;li&gt;練將會細心的了解您的運動狀況與生活型態。&lt;/li&gt;&lt;li&gt;教練將帶您期許的運動目標以及運動效果，讓您體驗愉快的課程。&lt;/li&gt;&lt;li&gt;教練將與您一同討論專屬於您的客製化訓練。&lt;/li&gt;.
        /// </summary>
        public static string FAQAnswer12 {
            get {
                return ResourceManager.GetString("FAQAnswer12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您可以透過以下方式聯繫我們完成您的首次體驗課程.
        /// </summary>
        public static string FAQAnswer13 {
            get {
                return ResourceManager.GetString("FAQAnswer13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 專業客製的訓練費用，以堂數做收費計算，規劃訓練價格會依照您的目標、規劃的時間長短及堂數而有所不同，價格約落在1500-2300不等。.
        /// </summary>
        public static string FAQAnswer21 {
            get {
                return ResourceManager.GetString("FAQAnswer21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeyondFitness 專注於1對1 客製化專業訓練，您無須再繳交任何月費、入會費及手續費。.
        /// </summary>
        public static string FAQAnswer22 {
            get {
                return ResourceManager.GetString("FAQAnswer22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Fitness的教練團隊為業界首屈一指的專業團隊， 所有相關人員皆俱備國際教練認證資格（國際證照且必須在有效期限內），內部專業團隊學術科考核（每季、半年、一年），以真誠認真的心搭配科學化訓練為根本、系統化紀錄、分析，讓每一位來運動的客戶感受最貼心且值得信任的服務。.
        /// </summary>
        public static string FAQAnswer3 {
            get {
                return ResourceManager.GetString("FAQAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 優良的私人教練是針對客戶的目標、生活作息、每一次的當天狀況做出客製化的訓練安排，同時給予您最好的訓練效果去幫助您達成改變並確實地避免運動傷害。&lt;br/&gt;&lt;br/&gt;最重要的並幫助您規劃您生活中其餘非運動時間需要注意的事項，相較於團體課程，教練更能針對客戶的目標去做訓練，並依照每位客戶的獨特性以及個別差異化進而給予最有效果的訓練哦！練，並依照每位客戶的獨特性進而給予最有效益的訓練哦！.
        /// </summary>
        public static string FAQAnswer4 {
            get {
                return ResourceManager.GetString("FAQAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以的 , 我們只提供 BeyondFitness的客戶登記使用喔，經由規劃專業自主訓練P.I Session，並且進行人數的管控以維持場地以提供客戶最好的運動品質。.
        /// </summary>
        public static string FAQAnswer5 {
            get {
                return ResourceManager.GetString("FAQAnswer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們樂於協助你，&lt;br /&gt;讓一切輕鬆又簡單。.
        /// </summary>
        public static string FAQBannerTitle {
            get {
                return ResourceManager.GetString("FAQBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我想瞭解私人教練課程內容？.
        /// </summary>
        public static string FAQQestion1 {
            get {
                return ResourceManager.GetString("FAQQestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否有體驗課程？.
        /// </summary>
        public static string FAQQestion11 {
            get {
                return ResourceManager.GetString("FAQQestion11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 課程內容是什麼呢？.
        /// </summary>
        public static string FAQQestion12 {
            get {
                return ResourceManager.GetString("FAQQestion12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我要如何預約呢？.
        /// </summary>
        public static string FAQQestion13 {
            get {
                return ResourceManager.GetString("FAQQestion13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 費用問題？.
        /// </summary>
        public static string FAQQestion2 {
            get {
                return ResourceManager.GetString("FAQQestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 課程內容是什麼呢？.
        /// </summary>
        public static string FAQQestion21 {
            get {
                return ResourceManager.GetString("FAQQestion21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我要如何預約呢？.
        /// </summary>
        public static string FAQQestion22 {
            get {
                return ResourceManager.GetString("FAQQestion22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond的團隊為何與眾不同？.
        /// </summary>
        public static string FAQQestion3 {
            get {
                return ResourceManager.GetString("FAQQestion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私人教練課程跟團體課程的差別？.
        /// </summary>
        public static string FAQQestion4 {
            get {
                return ResourceManager.GetString("FAQQestion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請問可以自己去Beyond運動嗎？.
        /// </summary>
        public static string FAQQestion5 {
            get {
                return ResourceManager.GetString("FAQQestion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Beyond Fitness提供以下承諾&lt;/p&gt;&lt;ul class=&quot;features-list&quot;&gt;&lt;li&gt;客製化課程內容，學習更安全，同時讓您得到顯著的運動效果&lt;/li&gt;&lt;li&gt;專業教練帶領下，清楚了解自己的身體狀況與運動進度&lt;/li&gt;&lt;li&gt;透過與您互相討論課程內容，強化掌握運動時的每個環節&lt;/li&gt;&lt;li&gt;固定時間評估並分析身體狀況與課程內容，隨時替您把關上課品質&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string Features1Desc {
            get {
                return ResourceManager.GetString("Features1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Beyond Fitness 團隊是業界擁有最多國際級六大專業證照的機構，讓您在專業及安全的環境下運動&lt;/p&gt;&lt;ul class=&quot;features-list&quot;&gt;&lt;li&gt;ACE   美國運動委員會&lt;/li&gt;&lt;li&gt;ACSM  美國運動醫學會&lt;/li&gt;&lt;li&gt;NCAA  國家委員會授證機構&lt;/li&gt;&lt;li&gt;NSCA  美國肌力體能協會&lt;/li&gt;&lt;li&gt;NASM  美國國家運動醫學會&lt;/li&gt;&lt;li&gt;CrossFit   美國混合健身系統&lt;/li&gt;&lt;li&gt;EXOS-XPS   美國最大私人運動員機構&lt;/li&gt;&lt;li&gt;CPR+AED    中華民國紅十字會&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string Features2Desc {
            get {
                return ResourceManager.GetString("Features2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Beyond Fitness成立以來，持續提供您運動時的相關分析，打造屬於您個人的體能分析庫&lt;/p&gt;&lt;ul class=&quot;features-list&quot;&gt;&lt;li&gt;體能分析庫，全面性分析您的運動與身體狀態&lt;/li&gt;&lt;li&gt;雲端課表內容，提供您更了解當下運動內容&lt;/li&gt;&lt;li&gt;實用的專業文章，隨時補充您的運動與健康資訊&lt;/li&gt;&lt;li&gt;有趣的運動小學堂，替您在運動後帶來不同的互動樂趣&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string Features3Desc {
            get {
                return ResourceManager.GetString("Features3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 南京店.
        /// </summary>
        public static string FindNanjingBranch {
            get {
                return ResourceManager.GetString("FindNanjingBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 台北市松山區南京東路四段17號B1.
        /// </summary>
        public static string FindNanjingBranchAdd {
            get {
                return ResourceManager.GetString("FindNanjingBranchAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位於台北小巨蛋正對面，鄰近微風百貨，小巨蛋商圈，捷運台北小巨蛋站1號出口，走路1分鐘即可抵達。.
        /// </summary>
        public static string FindNanjingBranchDesc1 {
            get {
                return ResourceManager.GetString("FindNanjingBranchDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 擁有超過百坪的專業場地，結合多樣化訓練設備，提供您在運動的同時不受一般場地侷限，讓您的訓練品質最佳化。.
        /// </summary>
        public static string FindNanjingBranchDesc2 {
            get {
                return ResourceManager.GetString("FindNanjingBranchDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分店一覽.
        /// </summary>
        public static string FindUs {
            get {
                return ResourceManager.GetString("FindUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信義店.
        /// </summary>
        public static string FindXinyiBranch {
            get {
                return ResourceManager.GetString("FindXinyiBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 台北市信義區信義路五段16號2樓之2.
        /// </summary>
        public static string FindXinyiBranchAdd {
            get {
                return ResourceManager.GetString("FindXinyiBranchAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位於台北101正對面，捷運台北101/世貿站3號出口即可抵達。.
        /// </summary>
        public static string FindXinyiBranchDesc1 {
            get {
                return ResourceManager.GetString("FindXinyiBranchDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 台北市獨一無二同時擁有室內與戶外的私人教練場地。專業、寬敞與隱私的訓練空間，並且結合戶外大草皮運動區與PU跑道，讓您不侷限於室內場地。同時擁有戶外區的運動空間，增加訓練項目多元化，讓健身不僅止於健身，而是更佳的生活與功能化。.
        /// </summary>
        public static string FindXinyiBranchDesc2 {
            get {
                return ResourceManager.GetString("FindXinyiBranchDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忠孝店.
        /// </summary>
        public static string FindZhongxiaoBranch {
            get {
                return ResourceManager.GetString("FindZhongxiaoBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 台北市大安區大安路一段75巷21號1F/B1.
        /// </summary>
        public static string FindZhongxiaoBranchAdd {
            get {
                return ResourceManager.GetString("FindZhongxiaoBranchAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位於頂好名店城後方大樓1F/B1，捷運忠孝復興站3號(地下街14號)出口，走路2分鐘即可抵達。.
        /// </summary>
        public static string FindZhongxiaoBranchDesc1 {
            get {
                return ResourceManager.GetString("FindZhongxiaoBranchDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 少數擁有室內挑高私人教練場地，明亮採光的運動空間，結合多樣化訓練設備，提供乾濕分離衛浴設備，方便您更舒適換穿衣物及梳洗。.
        /// </summary>
        public static string FindZhongxiaoBranchDesc2 {
            get {
                return ResourceManager.GetString("FindZhongxiaoBranchDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即前往.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即行動.
        /// </summary>
        public static string HereWeGo {
            get {
                return ResourceManager.GetString("HereWeGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源自於客戶每一分安心.
        /// </summary>
        public static string IndexBannerSubTitle {
            get {
                return ResourceManager.GetString("IndexBannerSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們的堅持.
        /// </summary>
        public static string IndexBannerTitle {
            get {
                return ResourceManager.GetString("IndexBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安心承諾.
        /// </summary>
        public static string IndexFeature1 {
            get {
                return ResourceManager.GetString("IndexFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 真正的專業來自於信任，我們專注於溝通及傾聽，與您攜手合作獲得成功。.
        /// </summary>
        public static string IndexFeature1Desc {
            get {
                return ResourceManager.GetString("IndexFeature1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 證照背書.
        /// </summary>
        public static string IndexFeature2 {
            get {
                return ResourceManager.GetString("IndexFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 擁有國際級六大專業證照，讓您在專業及安全的環境下運動。.
        /// </summary>
        public static string IndexFeature2Desc {
            get {
                return ResourceManager.GetString("IndexFeature2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 數據管理.
        /// </summary>
        public static string IndexFeature3 {
            get {
                return ResourceManager.GetString("IndexFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全新體能分析庫、個人化課表內容、每月挑戰，全為激發你的源源動力。.
        /// </summary>
        public static string IndexFeature3Desc {
            get {
                return ResourceManager.GetString("IndexFeature3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 數據體能分析，&lt;br /&gt;創造強而有力的新雲端.
        /// </summary>
        public static string IndexFunFactsTitle {
            get {
                return ResourceManager.GetString("IndexFunFactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 專業是細心且提升客戶的保障，Beyond 運動與物理治療的配合是有效的.
        /// </summary>
        public static string IndexSlick1Desc {
            get {
                return ResourceManager.GetString("IndexSlick1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 王妍萍.
        /// </summary>
        public static string IndexSlick1Name {
            get {
                return ResourceManager.GetString("IndexSlick1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物理治療師.
        /// </summary>
        public static string IndexSlick1Title {
            get {
                return ResourceManager.GetString("IndexSlick1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在溫馨與專業的Beyond，確保你的飲食以及運動都得到妥善照顧.
        /// </summary>
        public static string IndexSlick2Desc {
            get {
                return ResourceManager.GetString("IndexSlick2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 廖家祥.
        /// </summary>
        public static string IndexSlick2Name {
            get {
                return ResourceManager.GetString("IndexSlick2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 營養師.
        /// </summary>
        public static string IndexSlick2Title {
            get {
                return ResourceManager.GetString("IndexSlick2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 看看 黃伯伯 &lt;span class=&quot;hidden-sm-down&quot;&gt;和 陳阿姨 &lt;/span&gt;如何透過專業的訓練，更加了解運動的價值。.
        /// </summary>
        public static string IndexVedioDesc {
            get {
                return ResourceManager.GetString("IndexVedioDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夢想實踐者.
        /// </summary>
        public static string IndexVedioSubTitle {
            get {
                return ResourceManager.GetString("IndexVedioSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 給 不知道如何開始 背後的你.
        /// </summary>
        public static string IndexVedioTitle {
            get {
                return ResourceManager.GetString("IndexVedioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加入團隊.
        /// </summary>
        public static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請向Beyond Fitness自我介紹，如果有適合您的職缺，我們會與您聯繫。.
        /// </summary>
        public static string JoinUsContactDesc {
            get {
                return ResourceManager.GetString("JoinUsContactDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把握一展長才的機會.
        /// </summary>
        public static string JoinUsContactTitle {
            get {
                return ResourceManager.GetString("JoinUsContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Fitness 創立於 2014 年，致力於發展專業一對一私人教練。Beyond Fitness 從南京小巨蛋發跡，成立以來陸續拓展了信義 101 與忠孝敦化等分店，在這些的背後，是一群想用行動與專業實踐理想的夥伴，與背後願意相信 我們的客戶們。我們相信，教育應該是個別化的，訓練也應該是，我們針對個人化的需求去客製最符合「人」的訓練模式，進而引領客戶走向更美好的生活為目標。.
        /// </summary>
        public static string JoinUsDesc {
            get {
                return ResourceManager.GetString("JoinUsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微笑.
        /// </summary>
        public static string JoinUsFeature1 {
            get {
                return ResourceManager.GetString("JoinUsFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隨時隨地，熱情回饋.
        /// </summary>
        public static string JoinUsFeature1Desc {
            get {
                return ResourceManager.GetString("JoinUsFeature1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 啟發.
        /// </summary>
        public static string JoinUsFeature2 {
            get {
                return ResourceManager.GetString("JoinUsFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教學互長，一起成長.
        /// </summary>
        public static string JoinUsFeature2Desc {
            get {
                return ResourceManager.GetString("JoinUsFeature2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 溫暖.
        /// </summary>
        public static string JoinUsFeature3 {
            get {
                return ResourceManager.GetString("JoinUsFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如同家人般的關懷.
        /// </summary>
        public static string JoinUsFeature3Desc {
            get {
                return ResourceManager.GetString("JoinUsFeature3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正直.
        /// </summary>
        public static string JoinUsFeature4 {
            get {
                return ResourceManager.GetString("JoinUsFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 專業坦率，提供最真切的建議.
        /// </summary>
        public static string JoinUsFeature4Desc {
            get {
                return ResourceManager.GetString("JoinUsFeature4Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私人教練.
        /// </summary>
        public static string JoinUsJob1 {
            get {
                return ResourceManager.GetString("JoinUsJob1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string JoinUsJob1Desc {
            get {
                return ResourceManager.GetString("JoinUsJob1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行銷人員.
        /// </summary>
        public static string JoinUsJob2 {
            get {
                return ResourceManager.GetString("JoinUsJob2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string JoinUsJob2Desc {
            get {
                return ResourceManager.GetString("JoinUsJob2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加入執行團隊.
        /// </summary>
        public static string JoinUsTitle {
            get {
                return ResourceManager.GetString("JoinUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 了解更多.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 線上預約.
        /// </summary>
        public static string OnlineReservation {
            get {
                return ResourceManager.GetString("OnlineReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是把健康安放在最適當的位置.
        /// </summary>
        public static string OpportunityBannerSubTitle {
            get {
                return ResourceManager.GetString("OpportunityBannerSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸福.
        /// </summary>
        public static string OpportunityBannerTitle {
            get {
                return ResourceManager.GetString("OpportunityBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您將得到完整的內部教育培訓.
        /// </summary>
        public static string OpportunityFeaturesDesc1 {
            get {
                return ResourceManager.GetString("OpportunityFeaturesDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您將得到固定的國際進修機會.
        /// </summary>
        public static string OpportunityFeaturesDesc2 {
            get {
                return ResourceManager.GetString("OpportunityFeaturesDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您將了解科學雲端系統的數據.
        /// </summary>
        public static string OpportunityFeaturesDesc3 {
            get {
                return ResourceManager.GetString("OpportunityFeaturesDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您將獲得良好進修及升遷制度.
        /// </summary>
        public static string OpportunityFeaturesDesc4 {
            get {
                return ResourceManager.GetString("OpportunityFeaturesDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你可以獲得什麼.
        /// </summary>
        public static string OpportunityFeaturesTitle {
            get {
                return ResourceManager.GetString("OpportunityFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 了解團隊.
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選擇最適合您的方案.
        /// </summary>
        public static string PricingTitle {
            get {
                return ResourceManager.GetString("PricingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即預約.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 專業團隊.
        /// </summary>
        public static string TeamTitle {
            get {
                return ResourceManager.GetString("TeamTitle", resourceCulture);
            }
        }
    }
}
