//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.0.30319.1 自動產生。
// 
namespace WebHome.Models.MIG3_1.C0401 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1", IsNullable=false)]
    public partial class Invoice {
        
        /// <remarks/>
        public Main Main;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProductItem", IsNullable=false)]
        public DetailsProductItem[] Details;
        
        /// <remarks/>
        public Amount Amount;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public partial class Main {
        
        /// <remarks/>
        public string InvoiceNumber;
        
        /// <remarks/>
        public string InvoiceDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime InvoiceTime;
        
        /// <remarks/>
        public MainSeller Seller;
        
        /// <remarks/>
        public MainBuyer Buyer;
        
        /// <remarks/>
        public string CheckNumber;
        
        /// <remarks/>
        public BuyerRemarkEnum BuyerRemark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BuyerRemarkSpecified;
        
        /// <remarks/>
        public string MainRemark;
        
        /// <remarks/>
        public CustomsClearanceMarkEnum CustomsClearanceMark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomsClearanceMarkSpecified;
        
        /// <remarks/>
        public string Category;
        
        /// <remarks/>
        public string RelateNumber;
        
        /// <remarks/>
        public InvoiceTypeEnum InvoiceType;
        
        /// <remarks/>
        public string GroupMark;
        
        /// <remarks/>
        public DonateMarkEnum DonateMark;
        
        /// <remarks/>
        public string CarrierType;
        
        /// <remarks/>
        public string CarrierId1;
        
        /// <remarks/>
        public string CarrierId2;
        
        /// <remarks/>
        public string PrintMark;
        
        /// <remarks/>
        public string NPOBAN;
        
        /// <remarks/>
        public string RandomNumber;
        
        /// <remarks/>
        public MainContact Contact;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public partial class MainSeller {
        
        /// <remarks/>
        public string Identifier;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string PersonInCharge;
        
        /// <remarks/>
        public string TelephoneNumber;
        
        /// <remarks/>
        public string FacsimileNumber;
        
        /// <remarks/>
        public string EmailAddress;
        
        /// <remarks/>
        public string CustomerNumber;
        
        /// <remarks/>
        public string RoleRemark;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public partial class Amount {
        
        /// <remarks/>
        public long SalesAmount;
        
        /// <remarks/>
        public long FreeTaxSalesAmount;
        
        /// <remarks/>
        public long ZeroTaxSalesAmount;
        
        /// <remarks/>
        public TaxTypeEnum TaxType;
        
        /// <remarks/>
        public decimal TaxRate;
        
        /// <remarks/>
        public long TaxAmount;
        
        /// <remarks/>
        public long TotalAmount;
        
        /// <remarks/>
        public long DiscountAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscountAmountSpecified;
        
        /// <remarks/>
        public decimal OriginalCurrencyAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OriginalCurrencyAmountSpecified;
        
        /// <remarks/>
        public decimal ExchangeRate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExchangeRateSpecified;
        
        /// <remarks/>
        public CurrencyCodeEnum Currency;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencySpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public enum TaxTypeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1 = 1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2 = 2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3 = 3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4 = 4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9 = 9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public enum CurrencyCodeEnum {
        AED = 2,
        AFN = 204,
        ALL = 4,
        AMD = 5,
        ANG = 6,
        AOA = 7,
        ARS = 10,
        AUD = 12,
        AWG = 13,
        AZN = 205,
        BAM = 15,
        BBD = 16,
        BDT = 17,
        BGN = 20,
        BHD = 21,
        BIF = 22,
        BMD = 23,
        BND = 24,
        BOB = 25,
        BRL = 27,
        BSD = 28,
        BTN = 29,
        BWP = 30,
        BYR = 32,
        BZD = 33,
        CAD = 34,
        CDF = 35,
        CHF = 36,
        CLP = 38,
        CNY = 39,
        COP = 40,
        CRC = 41,
        CUP = 42,
        CVE = 43,
        CYP = 44,
        CZK = 45,
        DJF = 47,
        DKK = 48,
        DOP = 49,
        DZD = 50,
        EGP = 54,
        ERN = 55,
        ETB = 57,
        EUR = 58,
        FJD = 60,
        FKP = 61,
        GBP = 63,
        GEL = 64,
        GGP = 206,
        GHS = 207,
        GIP = 66,
        GMD = 67,
        GNF = 68,
        GTQ = 70,
        GYD = 72,
        HKD = 73,
        HNL = 74,
        HRK = 75,
        HTG = 76,
        HUF = 77,
        IDR = 78,
        ILS = 80,
        IMP = 208,
        INR = 81,
        IQD = 82,
        IRR = 83,
        ISK = 84,
        JEP = 209,
        JMD = 86,
        JOD = 87,
        JPY = 88,
        KES = 89,
        KGS = 90,
        KHR = 91,
        KMF = 92,
        KPW = 93,
        KRW = 94,
        KWD = 95,
        KYD = 96,
        KZT = 97,
        LAK = 98,
        LBP = 99,
        LKR = 100,
        LRD = 101,
        LSL = 102,
        LTL = 103,
        LVL = 105,
        LYD = 106,
        MAD = 107,
        MDL = 108,
        MGA = 210,
        MKD = 110,
        MMK = 111,
        MNT = 112,
        MOP = 113,
        MRO = 114,
        MTL = 115,
        MUR = 116,
        MVR = 117,
        MWK = 118,
        MXN = 119,
        MYR = 121,
        MZN = 211,
        NAD = 123,
        NGN = 124,
        NIO = 125,
        NOK = 127,
        NPR = 128,
        NZD = 129,
        OMR = 130,
        PAB = 131,
        PEN = 132,
        PGK = 133,
        PHP = 134,
        PKR = 135,
        PLN = 136,
        PYG = 138,
        QAR = 139,
        RON = 212,
        RSD = 213,
        RUB = 141,
        RWF = 143,
        SAR = 144,
        SBD = 145,
        SCR = 146,
        SDG = 214,
        SEK = 149,
        SGD = 150,
        SHP = 151,
        SLL = 154,
        SOS = 155,
        SPL = 215,
        SRD = 216,
        STD = 157,
        SVC = 158,
        SYP = 159,
        SZL = 160,
        THB = 161,
        TJS = 217,
        TMM = 163,
        TND = 164,
        TOP = 165,
        TRY = 218,
        TTD = 168,
        TVD = 219,
        TWD = 0,
        TZS = 169,
        UAH = 170,
        UGX = 171,
        USD = 172,
        UYU = 174,
        UZS = 175,
        VEB = 176,
        VEF = 203,
        VND = 177,
        VUV = 178,
        WST = 179,
        XAF = 180,
        XAG = 181,
        XAU = 182,
        XCD = 187,
        XDR = 188,
        XOF = 192,
        XPD = 193,
        XPF = 194,
        XPT = 195,
        YER = 197,
        ZAR = 199,
        ZMK = 200,
        ZWD = 202,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public partial class MainBuyer {
        
        /// <remarks/>
        public string Identifier;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string PersonInCharge;
        
        /// <remarks/>
        public string TelephoneNumber;
        
        /// <remarks/>
        public string FacsimileNumber;
        
        /// <remarks/>
        public string EmailAddress;
        
        /// <remarks/>
        public string CustomerNumber;
        
        /// <remarks/>
        public string RoleRemark;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public enum BuyerRemarkEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1=1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2=2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3=3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4=4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public enum CustomsClearanceMarkEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1=1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2=2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public enum InvoiceTypeEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01=01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02=02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03=03,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04=04,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05=05,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06=06,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07 = 07,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08 = 08,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public enum DonateMarkEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0=0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1=1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public partial class MainContact {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string TEL;
        
        /// <remarks/>
        public string Email;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:GEINV:eInvoiceMessage:C0401:3.1")]
    public partial class DetailsProductItem {
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public decimal Quantity;
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        public decimal UnitPrice;
        
        /// <remarks/>
        public decimal Amount;
        
        /// <remarks/>
        public string SequenceNumber;
        
        /// <remarks/>
        public string Remark;
        
        /// <remarks/>
        public string RelateNumber;
    }
}
